apiVersion: v1
kind: Service
metadata:
    name: web-svc
    labels:
        app: web
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 80
    selector:
        app: web