apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    tier: front-end
spec:
  selector:
    matchLabels:
      app: web
    replicas: 3
    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: web
        spec:
          containers:
            - image: nginx:latest
              name: web-page
              ports:
                - containerPort: 80